<body>
    <form method="post">
 
    <div>
        <h1>formulario</h1>
    </div>
    <label>nome</label><br>
    <input type="text" name="nome" placeholder="seu nome">
    <label><br></label>
    <label>senha</label><br>
    <input type="text" name="senha" placeholder="sua senha">
    <label><br></label>
    <label>email</label><br>
    <input type="text" name="email" placeholder="seu email">
    <label><br></label><br>
    <button type="submit">enviar</button>
    </form>
</body>
